services:
  graphql-server:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    command: yarn dev
